"""Structured Vision Schemas & Helpers.

Re-exports core environment models and defines structured output schema formats
for JARVIS Vision perception results.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

from vision.environment import (
    BoundingBox,
    CursorState,
    MonitorInfo,
    WindowInfo,
    UIElementType,
    UIElement,
    OCRTextItem,
    DetectedObject,
    FaceState,
    GestureType,
    GestureState,
    TableCell,
    DocumentStructure,
    ChartData,
    DiffSummary,
    EnvironmentState,
)


class StructuredVisionResult(BaseModel):
    """Structured response schema returned by VisionManager for Brain consumption."""

    source: str = Field(default="screen", description="Perception source: screen, camera, file")
    timestamp: str = Field(..., description="UTC ISO-8601 timestamp")
    active_application: str = Field(default="Unknown", description="Focused app name")
    active_window: str = Field(default="Unknown", description="Focused window title")
    screen: Dict[str, int] = Field(
        default_factory=lambda: {"width": 1920, "height": 1080},
        description="Screen dimensions"
    )
    visible_text: List[Dict[str, Any]] = Field(default_factory=list, description="OCR text blocks with bbox coordinates")
    ui_elements: List[Dict[str, Any]] = Field(default_factory=list, description="Detected UI controls with bbox coordinates")
    objects: List[Dict[str, Any]] = Field(default_factory=list, description="Detected physical or visual objects")
    description: str = Field(default="", description="Visual narrative generated by Vision LLM")
    confidence: float = Field(default=0.95, ge=0.0, le=1.0, description="Overall confidence level")
    provider: str = Field(default="unknown", description="Vision provider engine used")
    latency_ms: float = Field(default=0.0, description="Processing latency in milliseconds")


__all__ = [
    "BoundingBox",
    "CursorState",
    "MonitorInfo",
    "WindowInfo",
    "UIElementType",
    "UIElement",
    "OCRTextItem",
    "DetectedObject",
    "FaceState",
    "GestureType",
    "GestureState",
    "TableCell",
    "DocumentStructure",
    "ChartData",
    "DiffSummary",
    "EnvironmentState",
    "StructuredVisionResult",
]
